#include<stdio.h>
#include<conio.h>
void main()
{
clrscr();
int col,row;
col=30;
row=3;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=31;
row=3;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=32;
row=3;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=33;
row=3;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=34;
row=3;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=35;
row=3;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");


col=29;
row=4;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=29;
row=5;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=29;
row=6;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=29;
row=7;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=29;
row=8;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=29;
row=9;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=29;
row=10;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");





col=36;
row=4;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=36;
row=5;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=36;
row=6;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=36;
row=7;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=36;
row=8;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=36;
row=9;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=36;
row=10;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=30;
row=6;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=31;
row=6;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=32;
row=6;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=33;
row=6;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=34;
row=6;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=35;
row=6;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");


col=39;
row=4;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=39;
row=5;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=39;
row=6;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=39;
row=7;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=39;
row=8;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=39;
row=9;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=39;
row=10;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");





col=46;
row=4;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=46;
row=5;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=46;
row=6;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=46;
row=7;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=46;
row=8;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=46;
row=9;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=46;
row=10;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=39;
row=3;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=40;
row=3;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");


col=46;
row=3;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=41;
row=4;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=42;
row=5;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=43;
row=6;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=44;
row=7;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=45;
row=8;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ý");

col=45;
row=9;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Þ");

col=49;
row=4;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=49;
row=5;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=49;
row=6;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=49;
row=7;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=49;
row=8;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=49;
row=9;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=49;
row=10;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=49;
row=3;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=50;
row=7;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=51;
row=6;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=52;
row=5;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=53;
row=4;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=54;
row=3;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=51;
row=8;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=52;
row=9;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=53;
row=10;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");


col=54;
row=11;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");


col=26;
row=3;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=26;
row=4;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=26;
row=5;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=26;
row=6;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=26;
row=7;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=26;
row=8;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=26;
row=9;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=26;
row=10;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");


col=19;
row=3;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=19;
row=4;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=19;
row=5;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=19;
row=6;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=19;
row=7;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=19;
row=8;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=19;
row=9;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=19;
row=10;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");



col=20;
row=6;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=21;
row=6;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=22;
row=6;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=23;
row=6;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=24;
row=6;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=25;
row=6;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");


col=7;
row=3;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=8;
row=3;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=9;
row=3;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");


col=10;
row=3;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=11;
row=3;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=12;
row=3;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=13;
row=3;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=14;
row=3;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=15;
row=3;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=16;
row=3;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=11;
row=4;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=11;
row=5;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=11;
row=6;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=11;
row=7;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=11;
row=8;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=11;
row=9;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=11;
row=10;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");




col=57;
row=3;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=57;
row=4;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=57;
row=5;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=57;
row=6;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

/*col=57;
row=7;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=57;
row=8;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=57;
row=9;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=57;
row=10;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");*/


/*col=65;
row=3;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=65;
row=4;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=65;
row=5;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=65;
row=6;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");*/

col=65;
row=7;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=65;
row=8;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=65;
row=9;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=65;
row=10;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=58;
row=6;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=59;
row=6;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=60;
row=6;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=61;
row=6;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=62;
row=6;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=63;
row=6;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=64;
row=6;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");




col=58;
row=3;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=59;
row=2;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=60;
row=2;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=61;
row=2;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=62;
row=2;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=63;
row=2;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=64;
row=2;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=65;
row=3;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=64;
row=11;
gotoxy(col,row);
textcolor(GREEN);
cprintf("ß");

col=63;
row=11;
gotoxy(col,row);
textcolor(GREEN);
cprintf("ß");

col=62;
row=11;
gotoxy(col,row);
textcolor(GREEN);
cprintf("ß");

col=61;
row=11;
gotoxy(col,row);
textcolor(GREEN);
cprintf("ß");

col=60;
row=11;
gotoxy(col,row);
textcolor(GREEN);
cprintf("ß");

col=59;
row=11;
gotoxy(col,row);
textcolor(GREEN);
cprintf("ß");

col=58;
row=10;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");

col=57;
row=9;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=37;
row=17;
gotoxy(col,row);
textcolor(GREEN);
cprintf("BY");

col=35;
row=20;
gotoxy(col,row);
textcolor(GREEN);
cprintf("AANSHI");

/*col=29;
row=22;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=30;
row=22;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");


col=29;
row=24;
gotoxy(col,row);
textcolor(GREEN);
cprintf("ß");

col=30;
row=24;
gotoxy(col,row);
textcolor(GREEN);
cprintf("ß");

col=28;
row=23;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Þ");

col=28;
row=24;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Þ");

col=28;
row=25;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Þ");

col=31;
row=23;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ý");

col=31;
row=24;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ý");

col=31;
row=25;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ý");

/*col=29;
row=22;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=30;
row=22;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");


col=29;
row=24;
gotoxy(col,row);
textcolor(GREEN);
cprintf("ß");

col=30;
row=24;
gotoxy(col,row);
textcolor(GREEN);
cprintf("ß"); */



/*
col=33;
row=22;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=34;
row=22;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");


col=33;
row=24;
gotoxy(col,row);
textcolor(GREEN);
cprintf("ß");

col=34;
row=24;
gotoxy(col,row);
textcolor(GREEN);
cprintf("ß");


col=32;
row=23;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Þ");

col=32;
row=24;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Þ");

col=32;
row=25;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Þ");

col=35;
row=23;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ý");

col=35;
row=24;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ý");

col=35;
row=25;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ý");




col=36;
row=23;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ý");

col=36;
row=24;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ý");

col=36;
row=25;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ý");

col=39;
row=23;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ý");

col=39;
row=24;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ý");

col=39;
row=25;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ý");

col=36;
row=22;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=37;
row=23;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ý");

col=37;
row=24;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Þ");

col=38;
row=25;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Û");





col=41;
row=22;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");

col=41;
row=22;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ü");


col=40;
row=24;
gotoxy(col,row);
textcolor(GREEN);
cprintf("ß");

col=41;
row=24;
gotoxy(col,row);
textcolor(GREEN);
cprintf("ß");


col=40;
row=23;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Þ");

col=40;
row=24;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Þ");

col=40;
row=25;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Þ");

col=41;
row=23;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ý");

col=41;
row=24;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ý");

col=41;
row=25;
gotoxy(col,row);
textcolor(GREEN);
cprintf("Ý");*/










getch();
}
